name: Visionary X Bot
on:
  schedule:
    - cron: '0 */2 * * *' # ينشر خبراً كل ساعتين
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # تسمح للبوت بتعديل ملف الذاكرة وحفظه
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyTelegramBotAPI feedparser beautifulsoup4

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot.py

      - name: Save memory
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add published_urls.txt || echo "No changes"
          git commit -m "Update history [skip ci]" || echo "No changes"
          git push
